src/main/java/crafty/controller/HomeController.java
src/main/resources/static/css/registerGoods.css
src/main/webapp/WEB-INF/views/registerGoods.jsp

feat: generate registerGoods page

---

src/main/resources/static/css/findID.css
src/main/webapp/WEB-INF/views/findID.jsp

feat : generate findID/PW page

feat : generate findID page

---

src/main/resources/static/css/profileEdit.css
src/main/webapp/WEB-INF/views/profileEdit.jsp

feat: generate profile Edit page

feat: generate profile Edit page

---

src/main/resources/static/css/common.css

feat : generate common.css

---

src/main/webapp/WEB-INF/views/footer.jsp
src/main/webapp/WEB-INF/views/header.jsp

feat : generate header.jsp, footer.jsp

feat : generate header.jsp, footer.jsp

---

src/main/resources/static/css/common.css
src/main/webapp/WEB-INF/views/header.jsp

Develop 3 build header footer

---

src/main/resources/static/css/common.css

fix : common.css

---

src/main/java/crafty/controller/HomeController.java
src/main/java/crafty/pagination/dto/MainCard.java
src/main/java/crafty/pagination/dto/SearchKeyword.java
src/main/resources/static/css/mainLayout.css
src/main/webapp/WEB-INF/views/main.jsp

feat : generate main-page

---

src/main/resources/static/css/profileEdit.css
src/main/webapp/WEB-INF/views/profileEdit.jsp

fix: profileEdit

---

src/main/resources/static/css/registerGoods.css
src/main/webapp/WEB-INF/views/registerGoods.jsp

fix: registerGoods

---

src/main/webapp/WEB-INF/views/goodsDetail.jsp
src/main/webapp/resources/css/goodsDetail.css

feat:generate goodsDetail Page

feat:generate goodsDetail Page

---

src/main/resources/static/css/attendedGoodsDetail.css
src/main/webapp/WEB-INF/views/attendedGoodsDetail.jsp

feat: generate attendedGoodsDetail page

feat: generate attendedGoodsDetail page

---

src/main/resources/static/css/registeredGoodsDetail.css
src/main/webapp/WEB-INF/views/registeredGoodsDetail.jsp

feat: generate registeredGoodsDetail page

feat: generate registeredGoodsDetail page

---

src/main/resources/static/css/registeredGoodsSalesByItem.css
src/main/webapp/WEB-INF/views/registeredGoodsSalesByItem.jsp

feat: generate registeredGoodsSalesByItem page

feat: generate registeredGoodsSalesByItem page

---

src/main/resources/static/css/attendedGoods.css
src/main/resources/static/css/deleteRequest.css
src/main/resources/static/css/goodsManagement.css
src/main/resources/static/css/purchaserList.css
src/main/resources/static/css/registerRequest.css
src/main/resources/static/css/registeredGoods.css
src/main/webapp/WEB-INF/views/attendedGoods.jsp
src/main/webapp/WEB-INF/views/deleteRequest.jsp
src/main/webapp/WEB-INF/views/goodsManagement.jsp
src/main/webapp/WEB-INF/views/purchaserList.jsp
src/main/webapp/WEB-INF/views/registerRequest.jsp

rename: admin-registerRequest, admin-deleteRequest, admin-goodsManagement -> registerRequest, deleteRequest, goodsManagement
feat: attendedGoods, registeredGoods, registerRequest, deleteRequest, goodsManagement css file
delete: myPage.css
fix: attendedGoods, registeredGoods, registerRequest, deleteRequest, goodsManagement jsp
feat: generate purchaserList page

fix: list page

---

src/main/resources/static/css/attendedGoods.css
src/main/resources/static/css/attendedGoodsDetail.css
src/main/resources/static/css/deleteRequest.css
src/main/resources/static/css/goodsManagement.css
src/main/resources/static/css/purchaserList.css
src/main/resources/static/css/registerRequest.css
src/main/resources/static/css/registeredGoods.css
src/main/resources/static/css/registeredGoodsDetail.css
src/main/resources/static/css/registeredGoodsSalesByItem.css
src/main/webapp/WEB-INF/views/attendedGoods.jsp
src/main/webapp/WEB-INF/views/attendedGoodsDetail.jsp
src/main/webapp/WEB-INF/views/deleteRequest.jsp
src/main/webapp/WEB-INF/views/goodsDetail.jsp
src/main/webapp/WEB-INF/views/goodsManagement.jsp
src/main/webapp/WEB-INF/views/purchaserList.jsp
src/main/webapp/WEB-INF/views/registerRequest.jsp
src/main/webapp/WEB-INF/views/registeredGoodsDetail.jsp
src/main/webapp/WEB-INF/views/registeredGoodsSalesByItem.jsp
src/main/webapp/resources/css/goodsDetail.css

fix: profile 

---

src/main/java/crafty/pagination/dto/PageRequestDTO.java
src/main/java/crafty/pagination/dto/PageResponseDTO.java

feat: develop paginationDTO

---

src/main/resources/static/css/profile.css
src/main/webapp/WEB-INF/views/profile.jsp

Develop 15 build profile

---

src/main/resources/static/css/alarmedGoods.css
src/main/resources/static/css/likedGoods.css
src/main/webapp/WEB-INF/views/alarmedGoods.jsp
src/main/webapp/WEB-INF/views/likedGoods.jsp

feat: generate liked, alarm page

feat: generate liked, alarm page

---

src/main/java/crafty/dto/AdjustmentOrder.java
src/main/java/crafty/dto/DeliveryInfo.java
src/main/java/crafty/dto/Goods.java
src/main/java/crafty/dto/GoodsDesciptionImg.java
src/main/java/crafty/dto/Item.java
src/main/java/crafty/dto/Likes.java
src/main/java/crafty/dto/Member.java
src/main/java/crafty/dto/NondisclosureRequest.java
src/main/java/crafty/dto/OpenAlarm.java
src/main/java/crafty/dto/OrderItem.java
src/main/java/crafty/dto/Orders.java
src/main/java/crafty/dto/paymentInfo.java

feat: generate DTO

---

src/main/java/crafty/controller/APIController.java
src/main/java/crafty/controller/GoodsController.java
src/main/java/crafty/controller/LoginController.java
src/main/java/crafty/controller/MemberController.java
src/main/java/crafty/controller/NondisclosureController.java
src/main/java/crafty/controller/OrdersController.java

feat: generate Controller

---

src/main/java/crafty/mapper/AdjustmentOrderMapper.java
src/main/java/crafty/mapper/GoodsDescriptionImgMapper.java
src/main/java/crafty/mapper/GoodsMapper.java
src/main/java/crafty/mapper/ItemMapper.java
src/main/java/crafty/mapper/LikesMapper.java
src/main/java/crafty/mapper/MemberMapper.java
src/main/java/crafty/mapper/NondisclosureRequestMapper.java
src/main/java/crafty/mapper/OpenAlarmMapper.java
src/main/java/crafty/mapper/OrderItemMapper.java
src/main/java/crafty/mapper/OrdersMapper.java
src/main/java/crafty/mapper/PaymentInfoMapper.java
src/main/resources/mapper/AdjustmentOrderMapper.xml
src/main/resources/mapper/GoodsDescriptionImgMapper.xml
src/main/resources/mapper/GoodsMapper.xml
src/main/resources/mapper/ItemMapper.xml
src/main/resources/mapper/LikesMapper.xml
src/main/resources/mapper/MemberMapper.xml
src/main/resources/mapper/NondisclosureRequestMapper.xml
src/main/resources/mapper/OpenAlarmMapper.xml
src/main/resources/mapper/OrderItemMapper.xml
src/main/resources/mapper/OrdersMapper.xml
src/main/resources/mapper/PaymentInfoMapper.xml

feat: generate Mapper.java, Mapper.xml

feat: generate Mapper

---

src/main/java/crafty/service/AdjustmentOrderService.java
src/main/java/crafty/service/GoodsDescriptionImgService.java
src/main/java/crafty/service/GoodsService.java
src/main/java/crafty/service/ItemService.java
src/main/java/crafty/service/LikesService.java
src/main/java/crafty/service/MemberService.java
src/main/java/crafty/service/NodisclosureRequestService.java
src/main/java/crafty/service/OpenAlarmService.java
src/main/java/crafty/service/OrderItemService.java
src/main/java/crafty/service/OrdersService.java
src/main/java/crafty/service/PaymentInfoService.java

- MemberService
- GoodsService
- GoodsDescriptionImgService
- NondisclosureRequestService
- AdjustmentOrderService
- OrdersService
- OrderItemsService
- ItemService
- PaymentInfoService
- LikesService
- OpenAlarmService

feat: generate Service

---

src/main/webapp/WEB-INF/views/goodsDetail.jsp

fix : goodsDetail Page CalCulation Complete

fix : goodsDetail Page CalCulation Complete

---

src/main/resources/static/css/registerGoods.css
src/main/webapp/WEB-INF/views/registerGoods.jsp

fix: registerGoods page css

---

src/main/java/crafty/controller/GoodsController.java
src/main/java/crafty/mapper/GoodsMapper.java
src/main/java/crafty/pagination/dto/MainCard.java
src/main/java/crafty/pagination/dto/SearchKeyword.java
src/main/java/crafty/service/GoodsService.java
src/main/resources/mapper/GoodsMapper.xml
src/main/webapp/WEB-INF/views/main.jsp

feat : generate main page

---

HELP.md
src/main/java/crafty/controller/GoodsController.java
src/main/java/crafty/dto/Goods.java
src/main/java/crafty/dto/GoodsDesciptionImg.java
src/main/java/crafty/dto/GoodsResponse.java
src/main/java/crafty/dto/Item.java
src/main/java/crafty/dto/ItemResponse.java
src/main/java/crafty/service/GoodsDescriptionImgService.java
src/main/java/crafty/service/GoodsService.java
src/main/resources/static/css/registerGoods.css
src/main/webapp/WEB-INF/views/registerGoods.jsp

feat: get formdata use axios

---

src/main/java/crafty/controller/CraftyRestController.java
src/main/java/crafty/mapper/GoodsMapper.java
src/main/java/crafty/mapper/NondisclosureRequestMapper.java
src/main/java/crafty/service/GoodsService.java
src/main/java/crafty/service/NondisclosureRequestService.java
src/main/resources/mapper/GoodsMapper.xml
src/main/resources/mapper/NondisclosureRequestMapper.xml
src/main/webapp/WEB-INF/views/deleteRequest.jsp
src/main/webapp/WEB-INF/views/registerRequest.jsp

feat: 등록 요청 허가 / 불허, 비공개 요청 허가 / 불허

feat: 등록 요청 허가 / 불허, 비공개 요청 허가 / 불허

---

pom.xml
src/main/java/crafty/controller/LoginController.java
src/main/java/crafty/controller/MemberController.java
src/main/java/crafty/dto/Member.java
src/main/java/crafty/interceptor/SessionInterceptor.java
src/main/java/crafty/mapper/MemberMapper.java
src/main/java/crafty/repository/MemberRepository.java
src/main/java/crafty/service/MemberService.java
src/main/resources/application.properties
src/main/resources/mapper/MemberMapper.xml
src/main/resources/static/css/login.css
src/main/webapp/WEB-INF/views/find.jsp
src/main/webapp/WEB-INF/views/login.jsp
src/main/webapp/WEB-INF/views/signUp.jsp

fix : login, Member

---

src/main/java/crafty/controller/GoodsController.java
src/main/java/crafty/dto/MainCategoryList.java
src/main/java/crafty/mapper/GoodsMapper.java
src/main/java/crafty/pagination/dto/PageProperties.java
src/main/java/crafty/pagination/dto/PageResponseDTO.java
src/main/java/crafty/service/GoodsService.java
src/main/resources/mapper/GoodsMapper.xml
src/main/resources/static/css/mainLayout.css
src/main/webapp/WEB-INF/views/main.jsp

fix : main page -> 드롭다운, 카테고리, DB연동, 서칭, 페이지네이션

fix : main page -> 드롭다운, 카테고리, DB연동, 서칭, 페이지네이션

---

src/main/java/crafty/controller/MemberController.java
src/main/java/crafty/mapper/LikesMapper.java
src/main/java/crafty/mapper/OpenAlarmMapper.java
src/main/java/crafty/service/LikesService.java
src/main/java/crafty/service/OpenAlarmService.java
src/main/resources/mapper/LikesMapper.xml
src/main/resources/mapper/OpenAlarmMapper.xml
src/main/resources/static/css/alarmedGoods.css
src/main/resources/static/css/likedGoods.css
src/main/webapp/WEB-INF/views/alarmedGoods.jsp
src/main/webapp/WEB-INF/views/likedGoods.jsp

feat : generate like alarm

---

src/main/resources/mapper/GoodsMapper.xml

feat: update goodsMapper_ profile goods List

feat: update goodsMapper_ profile goods List

---

pom.xml
src/main/resources/static/css/card.css
src/main/resources/static/css/common.css
src/main/resources/static/css/mainLayout.css
src/main/resources/static/css/profile.css
src/main/resources/static/css/registerGoods.css
src/main/webapp/WEB-INF/views/main.jsp
src/main/webapp/WEB-INF/views/profile.jsp

fix: register, card, main

---

src/main/resources/static/css/goodsDetail.css
src/main/webapp/WEB-INF/views/goodsDetail.jsp

fix: item select dropdown

---

src/main/java/crafty/controller/LoginController.java
src/main/java/crafty/interceptor/SessionInterceptor.java
src/main/webapp/WEB-INF/views/login.jsp

fix : login

---

src/main/java/crafty/controller/CraftyRestController.java
src/main/java/crafty/controller/GoodsController.java
src/main/java/crafty/controller/MemberController.java
src/main/java/crafty/mapper/OrdersMapper.java
src/main/java/crafty/service/OrdersService.java
src/main/resources/mapper/GoodsMapper.xml
src/main/resources/mapper/OrdersMapper.xml
src/main/resources/static/css/mainLayout.css
src/main/webapp/WEB-INF/views/header.jsp

fix: memberId session

---

src/main/resources/mapper/GoodsMapper.xml

feat: goods registerRequest / deleteRequest Query

feat: goods registerRequest / deleteRequest Query

---

src/main/resources/mapper/GoodsMapper.xml

fix: main goodsMapper.xml getMainGoods, getMainGoodsTotalCount query

fix: main goodsMapper.xml getMainGoods, getMainGoodsTotalCount query

---

src/main/java/crafty/config/EmailConfig.java
src/main/java/crafty/controller/EmailController.java
src/main/java/crafty/controller/LoginController.java
src/main/java/crafty/controller/MemberController.java
src/main/java/crafty/dto/EmailRequest.java
src/main/java/crafty/dto/Member.java
src/main/java/crafty/mapper/MemberMapper.java
src/main/java/crafty/repository/MemberRepository.java
src/main/java/crafty/service/EmailService.java
src/main/java/crafty/service/MemberService.java
src/main/resources/application.properties
src/main/resources/mail/email.properties
src/main/resources/mapper/MemberMapper.xml
src/main/webapp/WEB-INF/views/find.jsp
src/main/webapp/WEB-INF/views/login.jsp
src/main/webapp/WEB-INF/views/profileEdit.jsp
src/main/webapp/WEB-INF/views/signUp.jsp

fix : login, sign up, findAccount, memberDto
feat : email(reset pw)

fix : login, sign up, findAccount, memberDto

---

src/main/java/crafty/controller/CraftyRestController.java
src/main/java/crafty/controller/MemberController.java
src/main/java/crafty/mapper/GoodsMapper.java
src/main/java/crafty/service/GoodsService.java
src/main/resources/application.properties
src/main/resources/mapper/GoodsMapper.xml
src/main/resources/static/css/common.css
src/main/webapp/WEB-INF/views/attendedGoods.jsp
src/main/webapp/WEB-INF/views/profile.jsp

fix: profile page pagination

---

src/main/resources/mapper/GoodsMapper.xml
src/main/resources/mapper/LikesMapper.xml
src/main/resources/mapper/OpenAlarmMapper.xml
src/main/webapp/WEB-INF/views/main.jsp

Develop 44 build main

---

src/main/java/crafty/dto/ResponseNondisclosureRequest.java
src/main/java/crafty/dto/ResponsePurchaserList.java
src/main/java/crafty/dto/ResponseRegisterRequest.java
src/main/resources/application.properties
src/main/webapp/WEB-INF/views/attendedGoods.jsp
src/main/webapp/WEB-INF/views/deleteRequest.jsp
src/main/webapp/WEB-INF/views/goodsDetail.jsp
src/main/webapp/WEB-INF/views/purchaserList.jsp
src/main/webapp/WEB-INF/views/registerRequest.jsp

fix: date format

---

src/main/java/crafty/controller/LoginController.java
src/main/java/crafty/controller/MemberController.java
src/main/java/crafty/dto/Member.java
src/main/java/crafty/mapper/MemberMapper.java
src/main/java/crafty/service/MemberService.java
src/main/webapp/WEB-INF/views/find.jsp

fix : find page, Member DTO, signUp page

fix : find page, Member DTO, signUp page

---

src/main/java/crafty/controller/ErrorController.java
src/main/java/crafty/controller/GlobalExceptionHandler.java
src/main/java/crafty/controller/GoodsController.java
src/main/java/crafty/controller/GoodsController.java.rej
src/main/java/crafty/dto/CustomException.java
src/main/java/crafty/dto/ErrorCode.java
src/main/java/crafty/dto/ErrorResponse.java
src/main/java/crafty/service/GoodsDescriptionImgService.java
src/main/java/crafty/service/GoodsService.java
src/main/java/crafty/service/ItemService.java
src/main/resources/application.properties
src/main/resources/mapper/GoodsMapper.xml
src/main/webapp/WEB-INF/views/error.jsp
src/main/webapp/WEB-INF/views/registerGoods.jsp

feat: generate Exception Handler, Exception dto, error page

feat: generate Exception Handler, Exception dto, error page

---

src/main/java/crafty/CraftyApplication.java
src/main/java/crafty/dto/AlarmedMemberEmail.java
src/main/java/crafty/mapper/GoodsMapper.java
src/main/java/crafty/mapper/MemberMapper.java
src/main/java/crafty/schedule/CraftyScheduling.java
src/main/resources/mapper/GoodsMapper.xml
src/main/resources/mapper/MemberMapper.xml
src/main/resources/mapper/OpenAlarmMapper.xml

feat: generate scheduling

---

src/main/java/crafty/controller/ErrorController.java
src/main/java/crafty/controller/GlobalExceptionHandler.java
src/main/java/crafty/dto/ErrorCode.java
src/main/java/crafty/dto/ErrorResponse.java
src/main/webapp/WEB-INF/views/registerGoods.jsp

feat: register Exception

---

src/main/resources/static/css/goodsDetail.css
src/main/resources/static/css/registerGoods.css
src/main/webapp/WEB-INF/views/goodsDetail.jsp
src/main/webapp/WEB-INF/views/registerGoods.jsp
src/main/webapp/WEB-INF/views/registeredGoodsDetail.jsp

fix: register goods, goodsDetail

fix: register goods, goodsDetail

---

src/main/resources/static/css/alarmedGoods.css
src/main/resources/static/css/attendedGoods.css
src/main/resources/static/css/card.css
src/main/resources/static/css/common.css
src/main/resources/static/css/likedGoods.css
src/main/resources/static/css/profile.css
src/main/resources/static/css/registeredGoods.css

fix : liked, alarmed, attended, registered css

fix : liked, alarmed, attended, registered css

---

src/main/resources/static/css/goodsDetail.css
src/main/webapp/WEB-INF/views/goodsDetail.jsp

fix: thumbnail overflow css

---

src/main/java/crafty/controller/CraftyRestController.java
src/main/java/crafty/mapper/MemberMapper.java
src/main/java/crafty/schedule/CraftyScheduling.java
src/main/java/crafty/service/OrdersService.java
src/main/resources/application.properties
src/main/resources/mapper/MemberMapper.xml
src/main/resources/static/css/attendedGoodsDetail.css

feat: add order 결제 확인 메일

---

src/main/webapp/WEB-INF/views/attendedGoodsDetail.jsp
src/main/webapp/WEB-INF/views/registeredGoods.jsp

feat: add 등록 굿즈 없을 때 문구

---

src/main/resources/static/css/registerGoods.css
src/main/webapp/WEB-INF/views/registerGoods.jsp

fix: register itemList

---

src/main/resources/application.properties
src/main/resources/static/css/mainLayout.css
src/main/resources/static/css/registerGoods.css
src/main/webapp/WEB-INF/views/error.jsp
src/main/webapp/WEB-INF/views/registerGoods.jsp

Develop 45 build register

---

src/main/resources/static/css/mainLayout.css
src/main/webapp/WEB-INF/views/main.jsp

fix : main search button

---

src/main/java/crafty/controller/LoginController.java
src/main/java/crafty/controller/MemberController.java
src/main/java/crafty/dto/ResponseProfile.java
src/main/java/crafty/mapper/MemberMapper.java
src/main/java/crafty/repository/MemberRepository.java
src/main/java/crafty/service/MemberService.java
src/main/resources/mapper/MemberMapper.xml
src/main/resources/static/css/login.css
src/main/webapp/WEB-INF/views/find.jsp
src/main/webapp/WEB-INF/views/profile.jsp
src/main/webapp/WEB-INF/views/profileEdit.jsp
src/main/webapp/WEB-INF/views/signUp.jsp

feat : signUp, validation(nickname, id, phoneNum, email)

fix : signUp page

---

src/main/java/crafty/dto/ResponseGoodsManagement.java
src/main/resources/mapper/GoodsMapper.xml
src/main/resources/static/css/mainLayout.css

fix: query, type

---

src/main/java/crafty/controller/GoodsController.java
src/main/java/crafty/service/OrdersService.java
src/main/resources/static/css/mainLayout.css
src/main/webapp/WEB-INF/views/registerRequest.jsp
src/main/webapp/WEB-INF/views/registeredGoodsDetail.jsp
src/main/webapp/WEB-INF/views/registeredGoodsSalesByItem.jsp

fix: html, css

---

src/main/java/crafty/controller/MemberController.java
src/main/java/crafty/mapper/MemberMapper.java
src/main/java/crafty/repository/MemberRepository.java
src/main/java/crafty/service/MemberService.java
src/main/resources/mapper/MemberMapper.xml
src/main/webapp/WEB-INF/views/attendedGoods.jsp
src/main/webapp/WEB-INF/views/find.jsp
src/main/webapp/WEB-INF/views/profile.jsp
src/main/webapp/WEB-INF/views/profileEdit.jsp
src/main/webapp/WEB-INF/views/signUp.jsp

Develop-54-profile edit
